- name: Install poetry
  shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
  args:
    warn: false

- name: Check if poetry config directory exist
  file:
    path: "{{ user_home }}/.config/pypoetry"
    state: directory

- name: Create symlink to config.toml
  file:
    src: "{{ dotfiles_home }}/poetry.toml"
    dest: "{{ user_home }}/.config/pypoetry/config.toml"
    state: link
    force: yes
