---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Add repos
      become: true
      apt_repository:
        repo: "{{ item }}"
      with_items: "{{ repos }}"

  tasks:
    - name: Install apt packages"
      become: true
      apt:
        name: "{{ item }}"
        state: latest
      with_items: "{{ apt }}"

    - name: Install pip packages
      become: true
      pip:
        name: "{{ item }}"
        state: latest
        executable: pip3
      with_items: "{{ pip }}"

    - name: Create dirs
      file: 
        path: "{{ item.dest }}"
        state: directory
      with_items: "{{ dirs }}"

    - name: Install oh-my-zsh
      become: true
      raw: sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    
    - name: Install zsh plugins and themes
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      with_items: "{{ git }}"

    - name: Install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.config/nvim/autoload/plug.vim
      
    - name: Backup all configs
      ignore_errors: yes
      command: mv "{{ item.dest }}" "{{ backup_dir }}/{{ item.name }}.backup"
      with_items: "{{ configs }}"
      when: not "item.dest.islnk"

    - name: Create symlinks for all dotfiles
      ignore_errors: yes
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items: "{{ configs }}"

    - name: Check if font exists
      stat:
        path: ~/.local/share/fonts/DejaVu Sans Mono Nerd Font Complete.ttf
      register: fontcheck

    - name: Download Dejavu Sans Mono Nerd Font
      command: curl -fLo "DejaVu Sans Mono Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DejaVuSansMono/Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete.ttf
      when: not fontcheck.stat.exists
    
    - name: Move fonts to fonts folder
      command: mv DejaVu\ Sans\ Mono\ Nerd\ Font\ Complete.ttf ~/.local/share/fonts/
      when: not fontcheck.stat.exists

    - name: Setup user shell
      become: true
      user: 
        name: "{{ lookup('env','USER') }}"
        shell: /usr/bin/zsh
