---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Add repos
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - "{{ repos }}"

  tasks:
    - name: Install apt packages"
      become: true
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - "{{ apt }}"

    - name: Install pip packages
      become: true
      pip:
        name: "{{ item }}"
        state: latest
        executable: pip3
      with_items:
        - "{{ pip }}"

    - name: Install oh-my-zsh and plugins
      raw: "{{ item }}"
      with_items:
        - sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
        - git clone git://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
        - git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k

    - name: Create backup folder
      file: path={{ backup_dest }} state=directory

    - name: Backup all dirs first
      command: mv "{{ item.src }}" "{{ backup_dest }}{{ item.src }}.backup"
      ignore_errors: yes
      with_items:
        - "{{ dirs }}"

    - name: Backup all configs
      ignore_errors: yes
      command: mv "{{ item.dest }}" "{{ backup_dest }}{{ item.dest }}.backup"
      with_items:
        - "{{ files }}"

    - name: Create neovim directory
      file: path={{ dirs.src }} state=directory

    - name: Create symlinks for all dotfiles
      file: path={{ item.src }} dest={{ item.dest }} state=link
      with_items:
        - "{{ files }}"



