---
- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Add repos
      become: true
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - "{{ repos }}"

  tasks:
    - name: Install apt packages"
      become: true
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - "{{ apt }}"

    - name: Install pip packages
      become: true
      pip:
        name: "{{ item }}"
        state: latest
        executable: pip3
      with_items:
        - "{{ pip }}"

    - name: Install oh-my-zsh
      raw: "{{ item }}"
      become: true
      with_items:
        - sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    
    - name: Install zsh-autosuggestions
      git:
        repo: git://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Install powerlevel9k zsh theme
      git:
       repo: https://github.com/bhilburn/powerlevel9k.git
       dest: ~/.oh-my-zsh/custom/themes/powerlevel9k

    - name: Create backup folder
      file: path={{ backup_dir }} state=directory

    - name: Backup all dirs first
      ignore_errors: yes
      command: mv "{{ item.src }}" "{{ backup_dir }}/{{ item.name }}.backup"
      with_items:
        - "{{ dirs }}"

    - name: Backup all configs
      ignore_errors: yes
      command: mv "{{ item.dest }}" "{{ backup_dir }}/{{ item.name }}.backup"
      with_items:
        - "{{ files }}"

    - name: Create dirs
      file: path={{ item.src }} state=directory
      with_items:
        - "{{ dirs }}"

    - name: Create symlinks for all dotfiles
      ignore_errors: yes
      file: src={{ item.src }} dest={{ item.dest }} state=link
      with_items:
        - "{{ files }}"

    - name: Install vim-plug
      command: curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      
    - name: Download Dejavu Sans Mono Nerd Font
      command: curl -fLo "DejaVu Sans Mono Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DejaVuSansMono/Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete.ttf
      
    - name: Create fonts folder
      file: path=~/.local/share/fonts/ state=directory
      
    - name: Move fonts to fonts folder
      command: mv DejaVu\ Sans\ Mono\ Nerd\ Font\ Complete.ttf ~/.local/share/fonts/

    - name: Setup user shell
      user: {{ lookup('env', 'USER') }}
      shell: {{ lookup('env', '(which zsh') }}
        
      

