- hosts: localhost

  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3
    ansible_retry_files_enabled: false
    ansible_validate_certs: false
    user_home: "{{ '~' | expanduser }}"
    dotfiles_home: "{{ user_home }}/dotfiles/files"

  roles:
    # Tag each role so that we can select individual roles to run with ansible-playbook --tags
    - { role: packages, tags: ["packages"] }
    - { role: wsl, tags: ["wsl"] }
    - { role: git, tags: ["git"] }
    - { role: zsh, tags: ["zsh"] }
    - { role: fzf, tags: ["fzf"] }
    - { role: tmux, tags: ["tmux"] }
    - { role: ranger, tags: ["ranger"] }
    - { role: cargo, tags: ["cargo"] }
    - { role: rg, tags: ["rg"] }
    - { role: fd, tags: ["fd"] }
    - { role: lsd, tags: ["lsd"] }
    - { role: duf, tags: ["duf"] }
    - { role: bat, tags: ["bat"] }
    - { role: tldr, tags: ["tldr"] }
    - { role: asn, tags: ["asn"] }
    - { role: go, tags: ["go"] }
    - { role: lua, tags: ["lua"] }
    - { role: poetry, tags: ["poetry"] }
    - { role: pip, tags: ["pip"] }
    - { role: fnm, tags: ["fnm"] }
    - { role: npm, tags: ["npm"] }
    - { role: nvim, tags: ["nvim"] }
    - { role: docker, tags: ["docker"] }
    - { role: pyenv, tags: ["pyenv"] }
