- name: Install pip packages
  pip:
    name:
      - httpie
      - ptpython
      - jedi
      - isort
      - mypy
      - flake8
      - autopep8
      - yapf
      - black
      - pynvim
      - jedi-language-server

- name: Creates .config/ptpython dir
  file:
    path: "{{ user_home }}/.config/ptpython"
    state: directory

- name: Create ptpython config symlink
  file:
    src: "{{ dotfiles_home }}/ptpython.py"
    dest: "{{ user_home }}/.config/ptpython/config.py"
    state: link

- name: Create .config/yapf dir
  file:
    path: "{{ user_home }}/.config/yapf"
    state: directory

- name: Symlink yapf config
  file:
    src: "{{ dotfiles_home }}/style.yapf"
    dest: "{{ user_home }}/.config/yapf/style"
    state: link
