- name: Install recommended dependencies for pyenv
  homebrew:
    name:
      - openssl
      - readline
      - sqlite3
      - xz
      - zlib
    state: present

- name: Install python2
  homebrew: name=python state=present

- name: Install python3
  homebrew: name=python3 state=present

- name: Install pyenv
  homebrew: name=pyenv state=present
  tags: pyenv

- name: Install pyenv-virtualenv
  homebrew: name=pyenv-virtualenv state=present
  tags: pyenv
