- name: Install ranger
  pip:
    name: ranger-fm
    state: latest

- name: Check if .config directory exist
  file:
    path: "{{ user_home }}/.config"
    state: directory

- name: Symlink ranger config
  file:
    src: "{{ dotfiles_home }}/ranger"
    dest: "{{ user_home }}/.config/ranger"
    # force: yes
    state: link
