- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh

- name: Create fonts dorectory
  file:
    path: "{{ user_home }}/.local/share/fonts/"
    state: directory

- name: Download Dejavu Sans Mono Nerd Font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DejaVuSansMono/Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete.ttf
    dest: ~/.local/share/fonts/DejaVu Sans Mono Nerd Font Complete.ttf

- name: Install zsh-autosuggestions
  git:
    repo: git://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Install POWERLEVEL10K theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
