- name: Install ohmyzsh
  git:
    repo: git@github.com:ohmyzsh/ohmyzsh.git
    dest: ~/.ohmyzsh

- name: Create fonts dorectory
  file:
    path: "{{ user_home }}/.local/share/fonts/"
    state: directory

- name: Download Dejavu Sans Mono Nerd Font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DejaVuSansMono/Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete.ttf
    dest: ~/.local/share/fonts/DejaVu Sans Mono Nerd Font Complete.ttf

- name: Install zsh-autosuggestions
  git:
    repo: git@github.com:zsh-users/zsh-autosuggestions.git
    dest: ~/.ohmyzsh/custom/plugins/zsh-autosuggestions

- name: Install POWERLEVEL10K theme
  git:
    repo: git@github.com:romkatv/powerlevel10k.git
    dest: ~/.ohmyzsh/custom/themes/powerlevel10k

- name: Install forgit plugin
  git:
    repo: git@github.com:wfxr/forgit.git
    dest: ~/.ohmyzsh/custom/plugins/forgit

- name: Install alias-tips plugin
  git:
    repo: git@github.com:djui/alias-tips.git
    dest: ~/.ohmyzsh/custom/plugins/alias-tips
