- name: Install go for Debian based systems
  block:
    - name: Add golang repo
      apt_repository:
        repo: ppa:longsleep/golang-backports
      when: >
        ansible_distribution == "Ubuntu" and
        ansible_distribution_version != "20.04"

    - name: Install golang
      apt:
        name:
          - golang-go
        state: latest
  become: yes
