- name: Check if go exists
  command: which go
  register: go
  failed_when: go.rc > 1
  changed_when: go.rc == 1

- name: Install go
  block:
    - name: Download go tarball
      unarchive:
        src: "{{ go_url }}{{ go_tar_file }}"
        dest: /usr/local/lib
        remote_src: yes
    - name: Create go symlink
      file:
        src: /usr/local/lib/go/bin/go
        dest: /usr/local/bin/go
        state: link
  become: yes
  when: go.rc == 1
