- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- name: Symlink .tmux.conf
  file:
    src: "{{ dotfiles_home }}/tmux.conf"
    dest: "{{ user_home }}/.tmux.conf"
    state: link

- name: Install TPM
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
