- name: Copy autohotkey script
  copy:
    src: autohotkey.ahk
    dest: /mnt/c/Users/{{ lookup('env', 'USER') }}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup
  when: ansible_env["WSLENV"] is defined
