# Multiline prefix
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{249}\u250f"
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{249}\u2517%F{default}"

# No prefixes
typeset -g POWERLEVEL9K_{CUSTOM_HOST,VCS,DIR,VIRTUALENV,PYENV,BATTERY}_PREFIX=

# Surrounding whitespace
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=' '

# Host block settings
case $ID in
  ubuntu)
    typeset -g POWERLEVEL9K_CUSTOM_HOST_BACKGROUND=166
    typeset -g POWERLEVEL9K_CUSTOM_HOST_FOREGROUND=229
    ;;
  debian)
    typeset -g POWERLEVEL9K_CUSTOM_HOST_BACKGROUND=229
    typeset -g POWERLEVEL9K_CUSTOM_HOST_FOREGROUND=197
    ;;
  centos)
    typeset -g POWERLEVEL9K_CUSTOM_HOST_BACKGROUND=160
    typeset -g POWERLEVEL9K_CUSTOM_HOST_FOREGROUND=000
    ;;
  manjaro)
    typeset -g POWERLEVEL9K_CUSTOM_HOST_BACKGROUND=041
    typeset -g POWERLEVEL9K_CUSTOM_HOST_FOREGROUND=000
    ;;
  arch)
    typeset -g POWERLEVEL9K_CUSTOM_HOST_BACKGROUND=238
    typeset -g POWERLEVEL9K_CUSTOM_HOST_FOREGROUND=039
    ;;
  *)
    typeset -g POWERLEVEL9K_CUSTOM_HOST_BACKGROUND=032
    typeset -g POWERLEVEL9K_CUSTOM_HOST_FOREGROUND=000
    ;;
esac

DEFAULT_GREY=237 # grey23

# User block settings
if [[ $USERNAME == "root" ]]; then
  typeset -g POWERLEVEL9K_CUSTOM_USER_BACKGROUND=88
  typeset -g POWERLEVEL9K_CUSTOM_USER_FOREGROUND=229
else
  typeset -g POWERLEVEL9K_CUSTOM_USER_BACKGROUND=203
  typeset -g POWERLEVEL9K_CUSTOM_USER_FOREGROUND=088
  # typeset -g POWERLEVEL9K_CUSTOM_USER_BACKGROUND=096
  # typeset -g POWERLEVEL9K_CUSTOM_USER_FOREGROUND=229
  # typeset -g POWERLEVEL9K_CUSTOM_USER_BACKGROUND=214
  # typeset -g POWERLEVEL9K_CUSTOM_USER_FOREGROUND=094
fi

# VCS block settings
typeset -g POWERLEVEL9K_VCS_FOREGROUND=$DEFAULT_GREY
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=142
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=167 #indianred
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=214 # orange1

# typeset -U POWERLEVEL9K_VCS_CONTENT_EXPANSION=

# typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION=
# typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR=$DEFAULT_GREY

# Dir block settings
# typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\UE0B0' # 
# typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\UE0B2' # 
# typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\UE0BC ' # 
# typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\UE0BA ' #
# typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B4' # 
# typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B6' # 
# typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0C6 ' # 
# typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0C7 ' # 
# typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0C0 ' # 
# typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0C2 ' #
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0C8 ' # 
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0Ca ' # 

typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B1' # 
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B3' # 
# typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B5' # 
# typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B7' # 
typeset -g POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{237} $(print_icon 'LEFT_SUBSEGMENT_SEPARATOR') %F{237}"

typeset -g POWERLEVEL9K_DIR_FOREGROUND=$DEFAULT_GREY
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND=$DEFAULT_GREY
typeset -g POWERLEVEL9K_DIR_BACKGROUND=033 # dodgerblue1

typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND=167
typeset -g POWERLEVEL9K_DIR_ETC_BACKGROUND=142

# Dir Writable settings
typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND=167
typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND=214

# Virtualenv block settings
typeset -g POWERLEVEL9K_{PYENV,VIRTUALENV}_FOREGROUND=004 # dodgerblue3
typeset -g POWERLEVEL9K_{PYENV,VIRTUALENV}_BACKGROUND=220 # gold1

# Battery background color
typeset -g POWERLEVEL9K_BATTERY_{LOW,CHARGING,CHARGED,DISCONNECTED}_BACKGROUND=$DEFAULT_GREY

# IP colors
typeset -g POWERLEVEL9K_IP_BACKGROUND=235
