# Multiline prefix
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{#bdae93}\u250f"
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{#bdae93}\u2517%F{default}"

# No prefixes
typeset -g POWERLEVEL9K_{CUSTOM_HOST,VCS,DIR,VIRTUALENV,PYENV,BATTERY}_PREFIX=

# Surrounding whitespace
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=' '

DEFAULT_GREY="#3c3836"

# Host block settings
case $ID in
  ubuntu)
    typeset -g POWERLEVEL9K_CUSTOM_HOST_BACKGROUND="#e46f08"
    typeset -g POWERLEVEL9K_CUSTOM_HOST_FOREGROUND=$DEFAULT_GREY
    ;;
  debian)
    typeset -g POWERLEVEL9K_CUSTOM_HOST_BACKGROUND="#fbf1c7"
    typeset -g POWERLEVEL9K_CUSTOM_HOST_FOREGROUND=$DEFAULT_GREY
    ;;
  centos)
    typeset -g POWERLEVEL9K_CUSTOM_HOST_BACKGROUND="#882076"
    typeset -g POWERLEVEL9K_CUSTOM_HOST_FOREGROUND=$DEFAULT_GREY
    ;;
  manjaro)
    typeset -g POWERLEVEL9K_CUSTOM_HOST_BACKGROUND="#4ebf57"
    typeset -g POWERLEVEL9K_CUSTOM_HOST_FOREGROUND=$DEFAULT_GREY
    ;;
  arch)
    typeset -g POWERLEVEL9K_CUSTOM_HOST_BACKGROUND="#368fcc"
    typeset -g POWERLEVEL9K_CUSTOM_HOST_FOREGROUND=$DEFAULT_GREY
    ;;
  *)
    typeset -g POWERLEVEL9K_CUSTOM_HOST_BACKGROUND="#368fcc"
    typeset -g POWERLEVEL9K_CUSTOM_HOST_FOREGROUND=$DEFAULT_GREY
    ;;
esac

# User block settings
if [[ $USERNAME == "root" ]]; then
  typeset -g POWERLEVEL9K_CUSTOM_USER_BACKGROUND="#fb4934"
  typeset -g POWERLEVEL9K_CUSTOM_USER_FOREGROUND=$DEFAULT_GREY
else
  typeset -g POWERLEVEL9K_CUSTOM_USER_BACKGROUND="#d78787"
  typeset -g POWERLEVEL9K_CUSTOM_USER_FOREGROUND=$DEFAULT_GREY
  # typeset -g POWERLEVEL9K_CUSTOM_USER_BACKGROUND="#fabd2f"
  # typeset -g POWERLEVEL9K_CUSTOM_USER_FOREGROUND=$DEFAULT_GREY
fi

# VCS block settings
typeset -g POWERLEVEL9K_VCS_FOREGROUND=$DEFAULT_GREY
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND="#b8bb26"
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="#fb4934"
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="#fabd2f"

# typeset -U POWERLEVEL9K_VCS_CONTENT_EXPANSION=

# typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION=
# typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR=$DEFAULT_GREY

# Dir block settings
# typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\UE0B0' # 
# typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\UE0B2' # 
# typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\UE0BC ' # 
# typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\UE0BA ' #
# typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B4' # 
# typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B6' # 
# typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0C6 ' # 
# typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0C7 ' # 
# typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0C0 ' # 
# typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0C2 ' #
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0C8 ' # 
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0Ca ' # 

typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B1' # 
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B3' # 
# typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B5' # 
# typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B7' # 
typeset -g POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{$DEFAULT_GREY} $(print_icon 'LEFT_SUBSEGMENT_SEPARATOR') %F{237}"

typeset -g POWERLEVEL9K_DIR_FOREGROUND=$DEFAULT_GREY
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND=$DEFAULT_GREY
typeset -g POWERLEVEL9K_DIR_BACKGROUND="#3385ff"

typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND="#fb4934"
typeset -g POWERLEVEL9K_DIR_ETC_BACKGROUND="#b8bb26"

# Dir Writable settings
typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="#fb4934"
typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="#fabd2f"

# Virtualenv block settings
typeset -g POWERLEVEL9K_{PYENV,VIRTUALENV}_FOREGROUND="#406b9c"
typeset -g POWERLEVEL9K_{PYENV,VIRTUALENV}_BACKGROUND="#f2cf3a"

# Battery background color
typeset -g POWERLEVEL9K_BATTERY_{LOW,CHARGING,CHARGED,DISCONNECTED}_BACKGROUND=$DEFAULT_GREY

# IP colors
typeset -g POWERLEVEL9K_IP_BACKGROUND=$DEFAULT_GREY
