- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

- name: Start docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes
  ignore_errors: yes

- name: Create docker group
  group:
    name: docker
    state: present
  become: yes

- name: Add current user to docker group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes
  become: yes

- name: Install docker-compose
  pip:
    name: docker-compose
    state: latest
  become: yes
