- name: Check if python exists
  command: which python
  register: python_check
  failed_when: python_check.rc > 1
  changed_when: python_check.rc == 1

- name: Save python3 path
  command: which python3
  register: python3_path
  failed_when: python3_path.rc > 1
  changed_when: python3_path.rc == 1

- name: Create python symlink
  file:
    src: python3_path.stdout
    dest: /usr/bin/python
    state: link
  become: yes
  when: python_check.rc == 1

- name: Download virtualenv
  get_url:
    url: https://bootstrap.pypa.io/virtualenv.pyz
    dest: ~/virtualenv.pyz
  when: python_check.rc == 1

- name: Create dev env
  shell: python ~/virtualenv.pyz ~/opt/venv
  when: python_check.rc == 1

- name: Remove virtualenv zipapp
  file:
    path: ~/virtualenv.pyz
    state: absent
  when: python_check.rc == 1
