- name: Add neovim repo
  apt_repository:
    repo: ppa:neovim-ppa/stable
  become: yes

- name: Install neovim
  apt:
    name:
      - python-dev
      - python-pip
      - python3-dev
      - python3-venv
      - python3-pip
      - neovim
    state: latest
  become: yes

- name: Install packages for plugins
  apt:
    name:
      - silversearcher-ag
      - cmake
      - exuberant-ctags
    state: latest
  become: yes

- name: Add Nodejs repo key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: yes

- name: Add Nodejs repo
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_13.x {{ ansible_distribution_release }} main'
  become: yes

- name: Install Nodejs
  apt:
    name: nodejs
    state: latest
  become: yes
