- name: Install NVIM from repo
  block:
    - name: Add NVIM repo for WSL
      apt_repository:
        repo: ppa:neovim-ppa/stable
      when: >
        ansible_env["WSLENV"] is defined and
        ansible_lsb["major_release"] == "18" and
        ansible_lsb["id"] == "Ubuntu"

    - name: Install NVIM for WSL
      apt:
        name:
          - neovim
        state: latest

  become: yes
  when: ansible_env["WSLENV"] is defined

- name: Install NVIM from Github
  get_url:
    url: "{{ nvim_release_url }}{{ nvim_version }}/{{ nvim_binary_file }}"
    dest: /usr/local/bin/nvim
    mode: "0755"
  become: yes
  when: >
    ansible_env["WSLENV"] is not defined
