- name: Install NVIM from repo
  block:
    - name: Add NVIM repo for WSL
      apt_repository:
        repo: ppa:neovim-ppa/stable

    - name: Install NVIM for WSL
      apt:
        name:
          - neovim
        state: latest

  become: yes
  when: ansible_env["WSLENV"] is defined

- name: Install packages for plugins
  apt:
    name:
      - cmake
      - exuberant-ctags
    state: latest
  become: yes

- name: Add Nodejs repo key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: yes

- name: Add Nodejs repo
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_13.x {{ ansible_distribution_release }} main'
  become: yes

- name: Install Nodejs
  apt:
    name: nodejs
    state: latest
  become: yes
