- name: Check if fd is installed
  command: dpkg-query -W fd
  register: fd_check_deb
  failed_when: fd_check_deb.rc > 1
  changed_when: fd_check_deb.rc == 1

- name: Install fd with a .deb file
  apt:
    deb: "{{ fd_release_url }}{{ fd_version }}/{{ fd_dpkg_file }}"
  become: yes
  when: fd_check_deb.rc == 1
